/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <SDL3Lite/Renders/Software/SoftwareRender.hpp>
#include <SDL3Lite/Renders/Software/SoftwareTexture.hpp>

using namespace SDL;

SoftwareRender::SoftwareRender(SDL_Window* window) :
	_window(window)
{
}

SDL_WindowFlags SoftwareRender::GetFlags()
{
	return _window->GetFlags();
}

const Vec2i& SoftwareRender::GetSize()
{
	return _window->GetSize();
}

void SoftwareRender::Present()
{
	_window->Present();
}

void SoftwareRender::SetColor(const Color& color)
{
	_color = color;
}

void SoftwareRender::Clear()
{
	_pixelPainter.Clear(_window->GetSurface(), _color);
}

void SoftwareRender::FillRect(const Vec2f& pos, const Vec2f& size)
{
	_pixelPainter.FillRect(_window->GetSurface(), pos, size, _color);
}

void SoftwareRender::Line(const SDL::Vec2f& first, const SDL::Vec2f& last)
{
	_pixelPainter.Line(_window->GetSurface(), first, last, _color);
}

void SoftwareRender::Draw(SDL_Texture* texture, const Rect2f& dst, const Rect2f& src)
{
	SDL_Rect dest   = { (int)dst.x, (int)dst.y, (int)dst.w, (int)dst.h };
	SDL_Rect source = { (int)src.x, (int)src.y, (int)src.w, (int)src.h };

	SoftwareTexture* surf = (SoftwareTexture*)texture;

	_pixelCopier.Copy(
		_window->GetSurface()->GetPixels(), 
		_window->GetSurface()->GetBpp(), 
		_window->GetSurface()->GetSize(), 
		Vec2i(dest.x, dest.y),
		Vec2i(dest.w, dest.h),
		surf->GetSurface()->GetPixels(),
		surf->GetSurface()->GetBpp(),
		surf->GetSurface()->GetSize(),
		Vec2i(source.x, source.y),
		Vec2i(source.w, source.h));
}
