/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef SDL3Lite_Types_h
#define SDL3Lite_Types_h

/**************************************************************************************
                                           Bool
**************************************************************************************/
#include <stddef.h>

#if (_MSC_VER >= 1900)
    #include <stdbool.h>
    #include <stdint.h>

    typedef int8_t   Sint8;
    typedef uint8_t  Uint8;

    typedef int16_t  Sint16;
    typedef uint16_t Uint16;

    typedef int32_t  Sint32;
    typedef uint32_t Uint32;

    typedef int64_t  Sint64;
    typedef uint64_t Uint64;
#else
    typedef signed char    Sint8;
    typedef unsigned char  Uint8;

    typedef signed short   Sint16;
    typedef unsigned short Uint16;

    typedef signed int     Sint32;
    typedef unsigned int   Uint32;

    typedef Sint32         Sint64;
    typedef size_t         Uint64;
#endif

#if (_MSC_VER <= 1200) && (!__cplusplus)
    #define bool  char
    #define true  1
    #define false 0
#endif

/**************************************************************************************
                                          Defines
**************************************************************************************/

#define SDLCALL

#if defined(_WIN32)
    #define SDL3LITE_EXPORT __declspec(dllexport)
    #define SDL3LITE_IMPORT __declspec(dllimport)
#elif defined(__unix__)
    #define SDL3LITE_EXPORT __attribute__((visibility("default")))
    #define SDL3LITE_IMPORT
#else
    #define SDL3LITE_EXPORT
    #define SDL3LITE_IMPORT
#endif

#if defined(SDL3LITE_STATIC)
    #define SDL_DECLSPEC
#else
    #if defined(SDL3LITE_SHARED)
        #define SDL_DECLSPEC SDL3LITE_EXPORT
    #else
        #define SDL_DECLSPEC SDL3LITE_IMPORT
    #endif
#endif

#endif
