/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <SDL3Lite/Platforms/Unix/MainWindow.hpp>

using namespace SDL;

const size_t eventMask = 
    PointerMotionMask
  | ButtonMotionMask
  | ButtonPressMask
  | ButtonReleaseMask
  | KeyPressMask
  | KeyReleaseMask;

MainWindow::MainWindow(Result& result, EventHandler& eventHandler, const Vec2i& pos, const Vec2i& size, const std::string& title, SDL_WindowFlags mode) :
	_result(&result),
	_eventHandler(&eventHandler),
	_baseWindow(pos, size, title),
	_EventMask(eventMask),
	_windowFlags(mode)
{
	_Display = XOpenDisplay(NULL);

	if (_Display == NULL)
		_result->Message("XOpenDisplay failed");

	_Screen = DefaultScreen(_Display);
	_Root = RootWindow(_Display, _Screen);
}

MainWindow::~MainWindow()
{
	XCloseDisplay(_Display);
}

const Vec2i& MainWindow::GetPos()
{
	return _baseWindow.GetPos();
}

void MainWindow::SetPos(const Vec2i& pos)
{
	_baseWindow.SetPos(pos);
}

const Vec2i& MainWindow::GetSize()
{
	return _baseWindow.GetSize();
}

void SDL::MainWindow::SetSize(const Vec2i& size)
{
	_baseWindow.SetSize(size);
}

const std::string& MainWindow::GetTitle()
{
	return _baseWindow.GetTitle();
}

void MainWindow::SetTitle(const std::string& title)
{
	_baseWindow.SetTitle(title);
}

SDL_WindowFlags MainWindow::GetWindowFlags()
{
	return _windowFlags;
}

void MainWindow::PollEvents()
{
	XEvent    event;
	SDL_Event report;
	size_t    key = 0;

	while (XPending(_Display))
	{
		XNextEvent(_Display, &event);

		/*
		switch (event.type)
		{
		case KeyPress:
			report.Type = LDL_Event::IsKeyboard;
			report.Keyboard.State = LDL_ButtonState::Pressed;
			key = ConvertKey(XKeycodeToKeysym(_Display, event.xkey.keycode, 0));
			report.Keyboard.Key = key;
			_Eventer.Push(report);
			break;

		case KeyRelease:
			report.Type = LDL_Event::IsKeyboard;
			report.Keyboard.State = LDL_ButtonState::Released;
			key = ConvertKey(XKeycodeToKeysym(_Display, event.xkey.keycode, 0));
			report.Keyboard.Key = key;
			_Eventer.Push(report);
			break;

		case MotionNotify:
			report.Type = LDL_Event::IsMouseMove;
			report.Mouse.PosX = event.xmotion.x;
			report.Mouse.PosY = event.xmotion.y;
			_Eventer.Push(report);
			break;

		case ButtonPress:
			report.Type = LDL_Event::IsMouseClick;
			report.Mouse.State = LDL_ButtonState::Pressed;

			size_t button = 0;

			switch (event.xbutton.button)
			{
			case 1:
				button = LDL_MouseButton::Left;
				break;
			case 2:
				button = LDL_MouseButton::Right;
				break;
			case 3:
				button = LDL_MouseButton::Middle;
				break;
			}

			report.Mouse.Button = button;
			report.Mouse.PosX = event.xbutton.x;
			report.Mouse.PosY = event.xbutton.y;
			_Eventer.Push(report);
			break;
		}
			*/
	}
}


Display* MainWindow::GetDisplay()
{
	return _Display;
}

int MainWindow::GetScreen()
{
	return _Screen;
}

Window MainWindow::GetRoot()
{
	return _Root;
}

Window MainWindow::GetWindow()
{
	return _Window;
}

void MainWindow::SetWindow(Window window)
{
	_Window = window;
}

size_t MainWindow::GetEventMask()
{
	return _EventMask;
}
