/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <assert.h>
#include <SDL3Lite/Application.hpp>
#include <SDL3Lite/IOStream.hpp>

using namespace SDL;

SDL_IOStream* SDL_IOFromFileImplementation(Result& result, const SDL::String& file, const SDL::String& mode)
{
	SDL_IOStream* ioStream = new IOStream(result);

	if (ioStream->IOFromFile(file, mode))
	{
		return ioStream;
	}

	delete ioStream;

	return NULL;
}

IOStream::IOStream(Result& result) :
	_result(result),
	_file(NULL)
{
}

IOStream::~IOStream()
{
}

bool IOStream::IOFromFile(const String& file, const String& mode)
{
	_file = fopen(file.c_str(), mode.c_str());

	return _file != NULL;
}

bool IOStream::CloseIO()
{
	return false;
}

size_t IOStream::ReadIO(void* ptr, size_t size)
{
	size_t result = fread(ptr, size, 1, _file);

	return result;
}


SDL_IOStream* SDL_IOFromFile(const char* file, const char* mode)
{
	return SDL_IOFromFileImplementation(SDL::GetApplication().GetResult(), file, mode);
}

bool SDL_CloseIO(SDL_IOStream* context)
{
	assert(context);

	context->CloseIO();

	delete context;

	return true;
}

size_t SDL_ReadIO(SDL_IOStream* context, void* ptr, size_t size)
{
	assert(context);

	return context->ReadIO(ptr, size);
}
