/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef SDL3Lite_OpenGLAttributes_hpp
#define SDL3Lite_OpenGLAttributes_hpp

namespace SDL
{
	class OpenGLAttributes
	{
	public:
		OpenGLAttributes();

		int GetRedSize();
		void SetRedSize(int value);

		int GetGreenSize();
		void SetGreenSize(int value);

		int GetBlueSize();
		void SetBlueSize(int value);

		int GetAlphaSize();
		void SetAlphaSize(int value);

		int GetAccumRedSize();
		void SetAccumRedSize(int value);

		int GetAccumGreenSize();
		void SetAccumGreenSize(int value);

		int GetAccumBlueSize();
		void SetAccumBlueSize(int value);

		int GetAccumAlphaSize();
		void SetAccumAlphaSize(int value);

		int GetMajor();
		void SetMajor(int value);

		int GetMinor();
		void SetMinor(int value);
	private:
		int _redSize;
		int _greenSize;
		int _blueSize;
		int _alphaSize;
		int _accumRedSize;
		int _accumGreenSize;
		int _accumBlueSize;
		int _accumAlphaSize;
		int _major;
		int _minor;
	};
}

#endif
