/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <SDL3Lite/OpenGL/GLUtils.hpp>
#include <assert.h>

namespace SDL
{
	const int TextureCount               = 12;
	const int TextureSizes[TextureCount] = { 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536 };

	int SelectTextureSize(const Vec2i& size)
	{
		int w = size.x;
		int h = size.y;

		for (int i = 0; i < TextureCount; i++)
		{
			if (w <= TextureSizes[i] && h <= TextureSizes[i])
			{
				return (int)TextureSizes[i];
			}
		}

		return 0;
	}

	void Normalize(const Color& color, GLclampf& r, GLclampf& g, GLclampf& b)
	{
		r = color.r / 255.0f;
		g = color.g / 255.0f;
		b = color.b / 255.0f;
	}

	GLuint CreateTexture(GLsizei width, GLsizei heigth, GLint format)
	{
		GLuint result = 0;

		GL_ASSERT(glGenTextures(1, (GLuint*)&result));

		GL_ASSERT(glEnable(GL_TEXTURE_2D));

		GL_ASSERT(glBindTexture(GL_TEXTURE_2D, (GLuint)result));

		GL_ASSERT(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST));
		GL_ASSERT(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST));

		GL_ASSERT(glTexImage2D(GL_TEXTURE_2D, 0, format, width, heigth, 0, format, GL_UNSIGNED_BYTE, NULL));

		GL_ASSERT(glDisable(GL_TEXTURE_2D));

		return result;
	}

	void DestroyTexture(GLint id)
	{
		GL_ASSERT(glDeleteTextures(0, (GLuint*)&id));
	}

	GLint BppToFormat(int bpp)
	{
		assert(bpp == 3 || bpp == 4);

		if (bpp == 3)
		{
			return GL_RGB;
		}
		else
		{
			return GL_RGBA;
		}
	}

	void CopyTexture(const Vec2i& dstPos, const Vec2i& srcSize, uint8_t* pixels, int bpp)
	{
		assert(pixels);

		GLint format = BppToFormat(bpp);

		GL_ASSERT(glTexSubImage2D(GL_TEXTURE_2D, 0, dstPos.x, dstPos.y, srcSize.x, srcSize.y, format, GL_UNSIGNED_BYTE, pixels));
	}

	void DrawTexture(const Vec2f& dstPos, const Vec2f& dstSize, const Vec2f& srcPos, const Vec2f& srcSize, size_t textureSize)
	{
		GLfloat x = dstPos.x;
		GLfloat y = dstPos.y;
		GLfloat w = dstSize.x;
		GLfloat h = dstSize.y;

		GLfloat cx = srcPos.x;
		GLfloat cy = srcPos.y;
		GLfloat cw = srcSize.x;
		GLfloat ch = srcSize.y;

		GLfloat dcx = cx / textureSize;
		GLfloat dcy = cy / textureSize;

		GLfloat dcw = (cx + cw) / textureSize;
		GLfloat dch = (cy + ch) / textureSize;

		glBegin(GL_QUADS);
		glTexCoord2f(dcx, dcy); glVertex2f(x, y);
		glTexCoord2f(dcw, dcy); glVertex2f(x + cw + (w - cw), y);
		glTexCoord2f(dcw, dch); glVertex2f(x + cw + (w - cw), y + ch + (h - ch));
		glTexCoord2f(dcx, dch); glVertex2f(x, y + ch + (h - ch));
		glEnd();
	}
}
