/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <string.h>
#include <SDL3Lite/OpenGL/Mat4f.hpp>

using namespace SDL;

Mat4f::Mat4f()
{
	Identity();
}

Mat4f& Mat4f::operator=(const Mat4f& source)
{
	if (this == &source)
	{
		return *this;
	}

	memcpy(&_values, source._values, sizeof(_values));

	return *this;
}

float* Mat4f::Values()
{
	return _values;
}

void Mat4f::Identity()
{
	_values[0] = 1;
	_values[1] = 0;
	_values[2] = 0;
	_values[3] = 0;
	_values[4] = 0;
	_values[5] = 1;
	_values[6] = 0;
	_values[7] = 0;
	_values[8] = 0;
	_values[9] = 0;
	_values[10] = 1;
	_values[11] = 0;
	_values[12] = 0;
	_values[13] = 0;
	_values[14] = 0;
	_values[15] = 1;
}

Mat4f Mat4f::operator * (const Mat4f& m) const {
	Mat4f ret;

	ret._values[0] = ((_values[0] * m._values[0]) + (_values[1] * m._values[4]) + (_values[2] * m._values[8]) + (_values[3] * m._values[12]));
	ret._values[1] = ((_values[0] * m._values[1]) + (_values[1] * m._values[5]) + (_values[2] * m._values[9]) + (_values[3] * m._values[13]));
	ret._values[2] = ((_values[0] * m._values[2]) + (_values[1] * m._values[6]) + (_values[2] * m._values[10]) + (_values[3] * m._values[14]));
	ret._values[3] = ((_values[0] * m._values[3]) + (_values[1] * m._values[7]) + (_values[2] * m._values[11]) + (_values[3] * m._values[15]));

	ret._values[4] = ((_values[4] * m._values[0]) + (_values[5] * m._values[4]) + (_values[6] * m._values[8]) + (_values[7] * m._values[12]));
	ret._values[5] = ((_values[4] * m._values[1]) + (_values[5] * m._values[5]) + (_values[6] * m._values[9]) + (_values[7] * m._values[13]));
	ret._values[6] = ((_values[4] * m._values[2]) + (_values[5] * m._values[6]) + (_values[6] * m._values[10]) + (_values[7] * m._values[14]));
	ret._values[7] = ((_values[4] * m._values[3]) + (_values[5] * m._values[7]) + (_values[6] * m._values[11]) + (_values[7] * m._values[15]));

	ret._values[8] = ((_values[8] * m._values[0]) + (_values[9] * m._values[4]) + (_values[10] * m._values[8]) + (_values[11] * m._values[12]));
	ret._values[9] = ((_values[8] * m._values[1]) + (_values[9] * m._values[5]) + (_values[10] * m._values[9]) + (_values[11] * m._values[13]));
	ret._values[10] = ((_values[8] * m._values[2]) + (_values[9] * m._values[6]) + (_values[10] * m._values[10]) + (_values[11] * m._values[14]));
	ret._values[11] = ((_values[8] * m._values[3]) + (_values[9] * m._values[7]) + (_values[10] * m._values[11]) + (_values[11] * m._values[15]));

	ret._values[12] = ((_values[12] * m._values[0]) + (_values[13] * m._values[4]) + (_values[14] * m._values[8]) + (_values[15] * m._values[12]));
	ret._values[13] = ((_values[12] * m._values[1]) + (_values[13] * m._values[5]) + (_values[14] * m._values[9]) + (_values[15] * m._values[13]));
	ret._values[14] = ((_values[12] * m._values[2]) + (_values[13] * m._values[6]) + (_values[14] * m._values[10]) + (_values[15] * m._values[14]));
	ret._values[15] = ((_values[12] * m._values[3]) + (_values[13] * m._values[7]) + (_values[14] * m._values[11]) + (_values[15] * m._values[15]));

	return ret;
}

SDL::Mat4f SDL::Ortho(float left, float right, float bottom, float top, float farv, float nearv)
{
	Mat4f result;

	result._values[0]  = (2.0f / (right - left));
	result._values[5]  = (2.0f / (top - bottom));
	result._values[10] = (-1.0);
	result._values[12] = (-(right + left) / (right - left));
	result._values[13] = (-(top + bottom) / (top - bottom));
	result._values[14] = (-(farv + nearv) / (farv - nearv));

	return result;
}
