/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <stdlib.h>
#include <SDL3/MemMngr.hpp>

MemoryManager::MemoryManager() :
	_mallocFunc(NULL),
	_callocFunc(NULL),
	_reallocFunc(NULL),
	_freeFunc(NULL)
{
	_mallocFunc  = &malloc;
	_callocFunc  = &calloc;
	_reallocFunc = &realloc;
	_freeFunc    = &free;
}

MemoryManager::~MemoryManager()
{
	_mallocFunc  = NULL;
	_callocFunc  = NULL;
	_reallocFunc = NULL;
	_freeFunc    = NULL;
}

bool MemoryManager::SetMemoryFunctions(SDL_malloc_func malloc_func, SDL_calloc_func calloc_func, SDL_realloc_func realloc_func, SDL_free_func free_func)
{
	_mallocFunc  = malloc_func;
	_callocFunc  = calloc_func;
	_reallocFunc = realloc_func;
	_freeFunc    = free_func;

	return true;
}

SDL_malloc_func MemoryManager::GetMalloc()
{
	return _mallocFunc;
}

SDL_calloc_func MemoryManager::GetCalloc()
{
	return _callocFunc;
}

SDL_realloc_func MemoryManager::GetRealloc()
{
	return _reallocFunc;
}

SDL_free_func MemoryManager::GetFree()
{
	return _freeFunc;
}
