/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <SDL3/StdInc.h>
#include <SDL3/PixPaint.hpp>

void PixelPainter::Clear(Surface* dest, const Color& color)
{
	size_t w        = dest->GetSize().x;
	size_t h        = dest->GetSize().y;
	size_t bpp      = dest->GetBpp();
	Uint8* pixels = dest->GetPixels();

	if (bpp == 3)
	{
		for (size_t i = 0; i < w * h * bpp; i += bpp)
		{
#if defined(_WIN32)
			pixels[i + 0] = color.b;
			pixels[i + 1] = color.g;
			pixels[i + 2] = color.r;
#else
			pixels[i + 0] = color.r;
			pixels[i + 1] = color.g;
			pixels[i + 2] = color.b;
#endif

		}
	}
}

void PixelPainter::FillRect(Surface* dest, const Vec2f& pos, const Vec2f& size, const Color& color)
{
	size_t x = (size_t)pos.x;
	size_t y = (size_t)pos.y;
	size_t w = (size_t)size.x;
	size_t h = (size_t)size.y;

	size_t surfW        = dest->GetSize().x;
	size_t surfH        = dest->GetSize().y;
	size_t surfBpp      = dest->GetBpp();
	Uint8* surfPixels = dest->GetPixels();

	if (surfBpp == 3)
	{
		for (size_t i = 0; i < size.x; i++)
		{
			for (size_t j = 0; j < size.y; j++)
			{
				size_t index = (surfW * (y + j) + (x + i)) * surfBpp;

				if (index < surfW * surfH * surfBpp)
				{
#if defined(_WIN32)
					surfPixels[index + 0] = color.b;
					surfPixels[index + 1] = color.g;
					surfPixels[index + 2] = color.r;
#else
					surfPixels[index + 0] = color.r;
					surfPixels[index + 1] = color.g;
					surfPixels[index + 2] = color.b;
#endif
				}
			}
		}
	}
}

void PixelPainter::Line(Surface* dest, const Vec2f& first, const Vec2f& last, const Color& color)
{
	int x1 = (int)first.x;
	int y1 = (int)first.y;

	int x2 = (int)last.x;
	int y2 = (int)last.y;

	size_t surfW      = dest->GetSize().x;
	size_t surfH      = dest->GetSize().y;
	size_t surfBpp    = dest->GetBpp();
	Uint8* surfPixels = dest->GetPixels();
	size_t index      = 0;

	int deltaX;
	int deltaY;
	int signX;
	int signY;
	int error;
	int error2;

	deltaX = SDL_abs(x2 - x1);
	deltaY = SDL_abs(y2 - y1);
	signX = x1 < x2 ? 1 : -1;
	signY = y1 < y2 ? 1 : -1;

	error = deltaX - deltaY;

	index = (surfW * (y2) + (x2)) * surfBpp;

	if (index < surfW * surfH * surfBpp)
	{
#if defined(_WIN32)
		surfPixels[index + 0] = color.b;
		surfPixels[index + 1] = color.g;
		surfPixels[index + 2] = color.r;
#else
		surfPixels[index + 0] = color.r;
		surfPixels[index + 1] = color.g;
		surfPixels[index + 2] = color.b;
#endif
	}

	while (x1 != x2 || y1 != y2)
	{
		index = (surfW * (y1)+(x1)) * surfBpp;

		if (index < surfW * surfH * surfBpp)
		{
#if defined(_WIN32)
			surfPixels[index + 0] = color.b;
			surfPixels[index + 1] = color.g;
			surfPixels[index + 2] = color.r;
#else
			surfPixels[index + 0] = color.r;
			surfPixels[index + 1] = color.g;
			surfPixels[index + 2] = color.b;
#endif
		}

		error2 = error * 2;

		if (error2 > -deltaY)
		{
			error -= deltaY;
			x1 += signX;
		}

		if (error2 < deltaX)
		{
			error += deltaX;
			y1 += signY;
		}
	}
}
