/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef SDL3Lite_Vector_hpp
#define SDL3Lite_Vector_hpp

#include <assert.h>
#include <SDL3/New.hpp>

template <class T>
class Vector
{
private:
	size_t _capacity;
	size_t _position;
	T*     _content;
	T*   allocate(size_t count);
	void deallocate(T* ptr);
public:
	Vector();
	~Vector();
	size_t capacity() const;
	size_t size() const;
	const T* data() const;
	T* data();
	void reserve(size_t count);
	void resize(size_t count);
	void clear();
	void push_back(const T& element);
	const T& at(size_t index) const;
	T& at(size_t index);
	const T& operator[] (size_t index) const;
	T& operator[] (size_t index);
};

template <class T>
T* Vector<T>::allocate(size_t count)
{
	return new T[count];
}

template <class T>
void Vector<T>::deallocate(T* ptr)
{
	delete[] _content;
}

template <class T>
Vector<T>::Vector() :
	_capacity(0),
	_position(0),
	_content(NULL)
{
}

template <class T>
Vector<T>::~Vector()
{
	deallocate(_content);
}

template <class T>
size_t Vector<T>::capacity() const
{
	return _capacity;
}

template <class T>
size_t Vector<T>::size() const
{
	return _position;
}

template <class T>
const T* Vector<T>::data() const
{
	return _content;
}

template <class T>
T* Vector<T>::data()
{
	return _content;
}

template <class T>
void Vector<T>::reserve(size_t count)
{
	if (count > _capacity)
	{
		T* p = allocate(count);

		for (size_t i = 0; i < _position; i++)
		{
			p[i] = _content[i];
		}

		if (_content != NULL)
		{
			deallocate(_content);
		}

		_content = p;
		_capacity = count;
	}
}

template <class T>
void Vector<T>::resize(size_t count)
{
	if (_capacity < count)
	{
		reserve(count);
	}

	_position = count;
}

template <class T>
void Vector<T>::clear()
{
	_position = 0;
}

template <class T>
void Vector<T>::push_back(const T& element)
{
	if (_capacity == 0)
	{
		reserve(2);
	}
	else if (_position + 1 >= _capacity)
	{
		reserve(_capacity * 2);
	}

	_content[_position] = element;

	_position++;
}

template <class T>
const T& Vector<T>::at(size_t index) const
{
	assert(index <= _position);

	return _content[index];
}

template <class T>
T& Vector<T>::at(size_t index)
{
	assert(index <= _position);

	return _content[index];
}

template <class T>
const T& Vector<T>::operator[] (size_t index) const
{
	assert(index <= _position);

	return _content[index];
}

template <class T>
T& Vector<T>::operator[] (size_t index)
{
	assert(index <= _position);

	return _content[index];
}

#endif
