/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef SDL3Lite_OpenGL_GLUtils_hpp
#define SDL3Lite_OpenGL_GLUtils_hpp

#include <OpenGL.h>
#include <SDL3Lite/Vec2.hpp>
#include <SDL3Lite/Rect2f.hpp>
#include <SDL3Lite/Color.hpp>

namespace SDL
{
	int SelectTextureSize(const Vec2i& size);
	void Normalize(const Color& color, GLclampf& r, GLclampf& g, GLclampf& b);
	GLuint CreateTexture(GLsizei width, GLsizei heigth, GLint format);
	void DestroyTexture(GLint id);
	GLint BppToFormat(int bpp);
	void CopyTexture(GLuint id, const Vec2i& dstPos, const Vec2i& srcSize, uint8_t* pixels, int bpp);
	void DrawTexture(const Rect2f& dst, const Rect2f& src, size_t textureSize);
}

#endif
